### ISSUE TITLE
Not working on Ubuntu.

### ISSUE THREAD

**Issue by thefirstofthe300** [welovewordpress/SublimePhpTidy#13]
For some reason, the plugin isn't working on Ubuntu.  I don't know if I missed something or if this plugin won't work on a Linux system.  

Currently I am getting the error code:
error: PhpTidy cannot find the script at /home/daniel/.config/sublime-text-2/Packages/PhpTidy/wp-phptidy.php.
Reloading plugin /home/daniel/.config/sublime-text-2/Packages/PhpTidy/php_tidy.py

I have check all of the file paths and they all SEEM to be okay.  I took a look at the Python file and that looks fine.  Anybody have any ideas?  I even reinstalled the pluging, restarted Sublime and it still doesn't work.  Anyone?

**Comment by tangram** [comment]
Try `chmod +x phptidy.php wp-phptidy.php` from the PhpTidy folder.

**Comment by thefirstofthe300** [comment]
I don't know why but I switched distros and it fixed the problem (switched to Arch).  Fixed now.

**Comment by pastinepolenta** [comment]
Same here , Ubuntu 12.04

**Comment by anmil** [comment]
I had the same issue in Ubuntu 14.04. I ran Sublime in the comsole and I got this message when trying to run Tidy `sh: 1: /usr/bin/php: not found` So I installed php and it work :)

Hope this helps
