### ISSUE TITLE
Formatting PHP-Doc Comments

### ISSUE THREAD

**Issue by sonOfRa** [welovewordpress/SublimePhpTidy#15]
When formatting PHP files, and there are oneline PHP-Doc Comments in them, phptidy produces Syntax Errors:

```
/** PHPDOC goes here */
function foo() 
  echo "bar";
}
```

Is turned into:

```
 * * * * /** PHPDOC goes here */
function foo() 
  echo "bar";
}
```

This seems to happen either when there is only one line of PHPDoc, or if the first line of the PHPDoc is not empty.

I'm running Sublime Text 2 Build 2217 on Ubuntu 12.10 amd64, installed PHPTidy via PackageControl

**Comment by swashata** [comment]
+1
