### ISSUE TITLE
Tidy for Sublime Text 3 ?

### ISSUE THREAD

**Issue by pyronaur** [welovewordpress/SublimePhpTidy#18]
I moved to ST3 rather quickly for some of its great new features, but I miss Tidy so bad. Any support for ST3 coming any time soon ?

**Comment by schickling** [comment]
Same here :+1:

**Comment by bafxyz** [comment]
i also have problems in ST3 win7 x64
PhpTidy: invoked on file: D:\My Documents\Dropbox\CSS\Duocom\my.class.php
PhpTidy: Ok, this seems to be PHP
PhpTidy: calling php.exe -v returned: 0
Traceback (most recent call last):
  File "D:\Web\PHP\Sublime Text\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "D:\Web\PHP\Sublime Text\Data\Packages\PhpTidy\php_tidy.py", line 53, in run
    fileHandle.write ( bufferContent ) 
TypeError: must be str, not bytes

**Comment by bafxyz** [comment]
same here

**Comment by sergeevabc** [comment]
Any progress here?

**Comment by Geczy** [comment]
Same issue here

**Comment by Geczy** [comment]
Fixed it myself, see pull here: https://github.com/welovewordpress/SublimePhpTidy/pull/21

**Comment by gautamgupta** [comment]
Note: This package doesn't show up in the Package Control on ST3.

**Comment by larsbo** [comment]
still not available with package control and sublime text 3

**Comment by rustanacexd** [comment]
how to install this manually?
