### ISSUE TITLE
Cannot find wp-phptidy.php

### ISSUE THREAD

**Issue by robrecord** [welovewordpress/SublimePhpTidy#24]
I get the error: PhpTidy cannot find the script at /Users/robrecord/Library/Application Support/Sublime Text 3/Packages/PhpTidy/wp-phptidy.php.

I looked in Packages and PhpTidy is not there, yet sublime text 3 reports it as installed.

**Comment by welovewordpress** [comment]
I'm afraid this extension is not compatible with Sublime Text 3 (yet). 

If anyone known enought Python and ST3 to create a proper extension (either ST3 only or compatible with both versions), you're very welcome to fork it and send pull requests. (Or submit a new ST3 version to the packages repository)

**Comment by robrecord** [comment]
Thanks!
