### ISSUE TITLE
Add support for other php files / extensions

### ISSUE THREAD

**Issue by AlexAndrascu** [welovewordpress/SublimePhpTidy#5]
Thanks for a very usefull plugin. 

If  you can add suport for other known php extensions that would be awsome. 

Currently i've modified the php_tidy.py around line 9

``` python
if FILE[-3:] == 'php' or 'module' or 'inc':
```

But i'm sure there's a better logic then using FILE variable.

**Comment by welovewordpress** [comment]
I've just included your patch for now. 

I'm no python expert but if someone comes around with a better way to check if the file is php, let me know.

**Comment by AlexAndrascu** [comment]
Thanks!

**Comment by welovewordpress** [comment]
Thanks @sc0tt you're great!
